### ISSUE TITLE
When run as regular user,  "show file extensions" is not a supported option

### ISSUE THREAD

**Issue by grrrrr** [securitywithoutborders/hardentools#101]
In Windows the option to show file extensions is done on an account by account basis.

In `v2.1-rc1` when you run hardentools as admin, the option is given to `Show File Extensions`.  This option is missing when you run hardentools without admin rights, though I don't believe there is any need for admin rights to set this on an account, at least any user can change this in `File Explorer`.

Windows 10: View” tab  -> “File name extensions"

Tested on Windows 10 Pro with hardentools v2.1-rc1

**Comment by obsti8383** [comment]
Has already been fixed with #95, but we did not publish a new version since then. Will publish a new version today.

**Comment by obsti8383** [comment]
Hi @grrrrr, that is strange. This should already be fixed with #95 in 2.1-rc1 and also works on my testclients. Are you using hardentools-cli.exe or hardentools.exe? Could you please upload a screenshot of your hardentools with expert settings enabled? And could you please also check that your exe is signed by "Florian Probst" on the 6th of April (see screenshot)?

![sign](https://user-images.githubusercontent.com/16605975/120888497-dd485b00-c5f8-11eb-914d-cea65c7854fa.jpg)
![hardenscreenshot](https://user-images.githubusercontent.com/16605975/120888499-df121e80-c5f8-11eb-87ae-03bdeddff03e.jpg)

**Comment by obsti8383** [comment]
Hi @grrrrr, could you verify this? Issue still open?

**Comment by obsti8383** [comment]
Closed due to issue not beeing reproducible
