### ISSUE TITLE
cli version wgl issues

### ISSUE THREAD

**Issue by brettowe** [securitywithoutborders/hardentools#109]
I was trying to run hardentools on an rather slow older laptop that apparently didn't have working opengl drivers.
I did try the cli version but running it without command line options apparently still tries to create a window.
in hind sight it might of been trying to create a window due to the command prompt window not being elevated.
also it didn't 'fail' and drop back to command line it was just sitting stalled like it was doing something.

the log just has the wgl creation error due to no opengl drivers mentioned in other bug reports.

**Comment by obsti8383** [comment]
Hi @brettowe,

yes, the only difference between the CLI version and the normal version is only a compiler-flag that suppresses any cmd.exe-Windows in the normal version.

If you don't handover one of the command line switches, it will still try to open the Window as normal and fail. Pity is that it just gets stuck because the UI framework doesn't give any feedback on this issue to our code. So there is currently no way around that behaviour that I'm aware off (other then changing the framework or maintaining two different code bases/branches).

Is `.\hardentools-cli.exe -harden` working fine for you?

Kind Regards,
Florian

**Comment by brettowe** [comment]
Thanks for the reply.
maybe add a check for the executable name being hardentools-cli.exe then just dump what would be the equivalent to "-help" if no options are passed and avoid any UI interaction?

I didn't know of -harden option when i had access to the laptop so I current don't know.
I'll see if I can get access to it again. it is likely to be several days before I can see it tho

**Comment by obsti8383** [comment]
@brettowe Just published a new beta versio (2.2-beta2). Would be great, if you find some time to test the new cli version.
