### ISSUE TITLE
Help Text Missing for CMD and LSA Protection

### ISSUE THREAD

**Issue by war59312** [securitywithoutborders/hardentools#120]
The Help Text screen is missing help for CMD and LSA Protection.

**Comment by obsti8383** [comment]
@war59312 You mean in the main screen help button that opens a separate window. If yes, this is by intend, because only the harden items will be listed which will be activated by the "Harden" button. CMD and LSA protection are only optional items which have to be enabled in the expert settings.
Is this not clear in the text ("The following hardenings will be activated by default...")? If yes I could add clearer text? Or would you expect help items for all items (also the non default ones)?

**Comment by war59312** [comment]
I'd expect help items for all, no matter what. Personally.

But I understand.

**Comment by obsti8383** [comment]
@war59312 OK, thanks a lot for the input. I will add the non-selected / non-default ones in the next release (without admin rights there appear even less items)
