### ISSUE TITLE
Question: Possible feature request?: Changes reversible? 

### ISSUE THREAD

**Issue by nickisghosty** [securitywithoutborders/hardentools#121]
Not an issue, just a question about the program.

Are the changes made by the program reversible using the program?
Or should I use a separate program that tracks the changes made in order to reverse what was done in case something breaks that I wish hadn't? 

If this isn't a feature, it would be a good thing to add in.

Ideally, you'd be able to run the program and tick/untick the features you want as needed. 

Thanks

**Comment by obsti8383** [comment]
Hi @nickisghosty, in case you wish to restore the original settings and revert the changes Hardentools made (for example, if you need to use cmd.exe), you can simply re-run the tool and instead of an "Harden" button you will be prompted with a "Harden again (all default settings)" and a "Restore..." button.

**Comment by nickisghosty** [comment]
Awesome.  I didn't see anything that mentioned this feature, which is why I posted it here.  and I didn't want to run it in case I wasn't able to do this. I appreciate the response.
