### ISSUE TITLE
Disable Office Equation calculator?

### ISSUE THREAD

**Issue by botherder** [securitywithoutborders/hardentools#52]
As you might have heard, the Equation calculator has been a subject of multiple vulnerabilities, e.g.:
https://embedi.com/blog/skeleton-closet-ms-office-vulnerability-you-didnt-know-about/

At the bottom of that posts the author provide registry key changes to disable that component. Perhaps it is worth adding them on?

**Comment by obsti8383** [comment]
I think normally that should not be exploitable, since the authors say "The only hindrance here is the protected view mode because it forbids active content execution (OLE/ActiveX/Macro)." (and we do all these). Anyhow it should be quite easy to implement.

Other thing: I think we could have an issue with our Office hardening in case of 32 Bit Office used on 64 Bit systems ("HKLM\SOFTWARE\Wow6432Node\[..]" would also have to be considered). I open a separate ticket for that.

**Comment by mschilt** [comment]
I think they completely removed the editor in one of the latest patch tuesdays. 
How about renaming the exe when its still there ?

**Comment by obsti8383** [comment]
Doesn't sound like hardening this makes much sense, since we already activated protected view mode and Microsoft removed it in 2018 with a patch.
