### ISSUE TITLE
How much additional LSA Protection and ASR hit performance?

### ISSUE THREAD

**Issue by necros2k7** [securitywithoutborders/hardentools#85]
subj

**Comment by obsti8383** [comment]
@necros2k7 What exactly is your question? Do LSA Protection and ASR impact performance of Windows in a negative way? If yes, I can't answer this. Since these are "only" additional security controls that e.g. prevent drivers accessing the LSA and the execution of malicious office document content, I don't believe there is really a performance impact. But you'd have to ask Microsoft to be sure.

References:
[https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
[https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/attack-surface-reduction)
