### ISSUE TITLE
Please document all changes

### ISSUE THREAD

**Issue by atlantsecurity** [securitywithoutborders/hardentools#92]
Please document all registry and policy changes being done by the tool to allow for automation OR enable command-line hardening, where each option is a command line switch which can be turned off or on.

**Comment by obsti8383** [comment]
@atlantsecurity Please be careful, hardentools is not designed for being deployed in a company environment. It is really designed to be used by the user that is currently logged in (won't work if you only deploy it via an admin user, since quite a lot of the settings are user specific). However we already prepared #90, which allows to harden with the default settings.
